### ISSUE TITLE
Add sync or mirror functionality to data store

### ISSUE THREAD

**Issue by gbdrummer** [ngnjs/ngn-core#1]
We currently don't have an automated way to relay events from one store to another. For example, if I am storing different pieces of data about a particular UI element in multiple different stores, we now have to manually track down the data in each store and update it.

It would be nice to have a way to link different bits of data in different stores.

**Comment by coreybutler** [comment]
Perhaps something similar to the reactions concept from the `NGNX.VIEW.Registry` would make sense here?

**Comment by coreybutler** [comment]
Ping @gbdrummer.

**Comment by coreybutler** [comment]
Kamino closed and cloned this issue to [ngnjs/NGN](https://github.com/ngnjs/NGN/issues/53)
